import CategoryNews from "../components/CategoryNews"

const TechnologyFilter = () => {
    return (
        <div className="normalWidth mx-auto mt-5 d-flex flex-column gap-4">
            <CategoryNews path="/empresa-de-tecnologia-lanca-celular" title="Empresa de tecnologia lança novo smartphone com recursos inovadores" author="Carolina Oliveira | 10/03/2023" content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum assumenda beatae natus quaerat adipisci a explicabo ratione voluptatum, laboriosam, repellat eligendi eius aut libero in quis voluptatibus veniam asperiores molestias nesciunt tempora mollitia? Debitis pariatur sapiente quisquam. Asperiores magni nobis nemo corporis, reprehenderit velit omnis eos sed, est voluptatibus similique?"/>
            <CategoryNews path="/pesquisadores-desenvolvem-ia" title="Pesquisadores desenvolvem inteligência artificial capaz de superar humanos em jogo de estratégia" author="Lucas Santos | 10/03/2023" content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum assumenda beatae natus quaerat adipisci a explicabo ratione voluptatum, laboriosam, repellat eligendi eius aut libero in quis voluptatibus veniam asperiores molestias nesciunt tempora mollitia? Debitis pariatur sapiente quisquam. Asperiores magni nobis nemo corporis, reprehenderit velit omnis eos sed, est voluptatibus similique?"/>
            <CategoryNews path="/avancos-na-realidade-virtual" title="Avanços na área de realidade virtual revolucionam a experiência do usuário" author="Gabriela Silva | 22/05/2023" content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum assumenda beatae natus quaerat adipisci a explicabo ratione voluptatum, laboriosam, repellat eligendi eius aut libero in quis voluptatibus veniam asperiores molestias nesciunt tempora mollitia? Debitis pariatur sapiente quisquam. Asperiores magni nobis nemo corporis, reprehenderit velit omnis eos sed, est voluptatibus similique?"/>
            <CategoryNews path="/startups-de-inteligencia-investimento" title="Startups de inteligência artificial recebem investimento milionário de grandes empresas" author="Pedro Fernandes | 15/07/2023" content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum assumenda beatae natus quaerat adipisci a explicabo ratione voluptatum, laboriosam, repellat eligendi eius aut libero in quis voluptatibus veniam asperiores molestias nesciunt tempora mollitia? Debitis pariatur sapiente quisquam. Asperiores magni nobis nemo corporis, reprehenderit velit omnis eos sed, est voluptatibus similique?"/>
            <CategoryNews path="/dispositivo-wearable-monitora-saude" title="Novo dispositivo wearable monitora saúde e bem-estar dos usuários em tempo real" author="Lucas Ferreira | 22/09/2023" content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum assumenda beatae natus quaerat adipisci a explicabo ratione voluptatum, laboriosam, repellat eligendi eius aut libero in quis voluptatibus veniam asperiores molestias nesciunt tempora mollitia? Debitis pariatur sapiente quisquam. Asperiores magni nobis nemo corporis, reprehenderit velit omnis eos sed, est voluptatibus similique?"/>
        </div>
    )
}

export default TechnologyFilter