const AboutInfo = () => {
    return(
        <>
            <div className="smallWidth mx-auto lineContainer gap-sm-5 d-sm-flex flex-row mt-4">
                <p className="aboutParagraph">Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, quidem reiciendis obcaecati alias atque pariatur dolor numquam possimus cum optio harum ullam error nisi illo mollitia impedit tempora vel modi sed doloribus eaque accusamus! Rerum temporibus molestiae porro veritatis beatae nulla, modi repudiandae reprehenderit quo, excepturi eaque alias iste voluptates ad vero exercitationem placeat ab debitis. Quia nulla odit omnis culpa, magni repudiandae quos. Nobis distinctio accusamus voluptatibus corporis praesentium nostrum officiis iusto, velit obcaecati! Asperiores maiores corporis incidunt reprehenderit iure accusantium natus. Blanditiis porro, veritatis animi dolorum aperiam provident culpa architecto fugit quos. Corrupti distinctio autem beatae! Eum, repellendus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, quidem reiciendis obcaecati alias atque pariatur dolor numquam possimus cum optio harum ullam error nisi illo mollitia impedit tempora vel modi sed doloribus eaque accusamus! Rerum temporibus molestiae porro veritatis beatae nulla, modi repudiandae reprehenderit quo, excepturi eaque alias iste voluptates ad vero exercitationem placeat ab debitis. Quia nulla odit omnis culpa, magni repudiandae quos. Nobis distinctio accusamus voluptatibus corporis praesentium nostrum officiis iusto, velit obcaecati! Asperiores maiores corporis incidunt reprehenderit iure accusantium natus. Blanditiis porro, veritatis animi dolorum aperiam provident culpa architecto fugit quos. Corrupti distinctio autem beatae! Eum, repellendus?</p>
                <div className="aboutImage1 "></div>
            </div>
            <div className="d-flex flex-column flex-sm-row lineContainer gap-sm-5 mt-5 smallWidth mx-auto">
                <div className="aboutImage2 order-2 order-sm-1"></div>
                <p className="aboutParagraph  order-1 order-sm-2 p-0 m-0">Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, quidem reiciendis obcaecati alias atque pariatur dolor numquam possimus cum optio harum ullam error nisi illo mollitia impedit tempora vel modi sed doloribus eaque accusamus! Rerum temporibus molestiae porro veritatis beatae nulla, modi repudiandae reprehenderit quo, excepturi eaque alias iste voluptates ad vero exercitationem placeat ab debitis. Quia nulla odit omnis culpa, magni repudiandae quos. Nobis distinctio accusamus voluptatibus corporis praesentium nostrum officiis iusto, velit obcaecati! Asperiores maiores corporis incidunt reprehenderit iure accusantium natus. Blanditiis porro, veritatis animi dolorum aperiam provident culpa architecto fugit quos. Corrupti distinctio autem beatae! Eum, repellendus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, quidem reiciendis obcaecati alias atque pariatur dolor numquam possimus cum optio harum ullam error nisi illo mollitia impedit tempora vel modi sed doloribus eaque accusamus! Rerum temporibus molestiae porro veritatis beatae nulla, modi repudiandae reprehenderit quo, excepturi eaque alias iste voluptates ad vero exercitationem placeat ab debitis. Quia nulla odit omnis culpa, magni repudiandae quos. Nobis distinctio accusamus voluptatibus corporis praesentium nostrum officiis iusto, velit obcaecati! Asperiores maiores corporis incidunt reprehenderit iure accusantium natus. Blanditiis porro, veritatis animi dolorum aperiam provident culpa architecto fugit quos. Corrupti distinctio autem beatae! Eum, repellendus?</p>
            </div>
        </>
    )
}

export default AboutInfo